### PR TITLE
Updated README.md with smtp, host info for .env file

### PR DESCRIPTION
**Pull request by arifulhb**
Added additional info in README.md file which shell be helpful to developers..

### CODE REVIEW

**Comment by emilsundberg** [comment]
That's not how this driver works. You defined your api key in `services.php` and not in your `.env`. It doesn't matter which `MAIL_USERNAME` you use.

**Comment by arifulhb** [comment]
hmm.. but I don't wanted to put the api key in `services.php`  as that will be under git commit. I took the api key from env and used in `service.php`.  Also I may not aware of other way to send email, without specifying `$mail->from(env('MAIL_USERNAME'), appTitle(). ' Test Mail')` , thats why I used in this way and it worked. I tested setting other mail address in `MAIL_USERNAME` but received 

    Exception in Api.php line 123: Postmark delivery failed: Sender signature not defined for From address.

**Comment by hkdobrev** [comment]
@arifulhb You can always use `getenv()` in the actual config file and still use `.env`, but this is not related to this package, but how _you_ configure it in _your_ application.

**Comment by emilsundberg** [comment]
You can define postmark in `services.php` like this:

```php
'postmark' => [
        'api_key' => env('POSTMARK_API_KEY'),
],
```

Then in your `.env` add:

`POSTMARK_API_KEY=YOUR_API_KEY_HERE`

**Pull request closed without merging**
